[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "snbpy"
authors = [{name = "Snowball Securities", email = "xueyingdeveloper@xueqiu.com"}]
dynamic = ["version", "description"]
